# Generated by Django 2.0 on 2018-08-20 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liblist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookcheckoutstatus', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete='models.CASCADE', to='libapp.Book')),
                ('member', models.ForeignKey(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
