# Generated by Django 2.0 on 2018-08-21 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0002_liblist'),
    ]

    operations = [
        migrations.AddField(
            model_name='liblist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 21, 19, 2, 4, 211543)),
        ),
    ]
