# Generated by Django 2.0 on 2018-08-21 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_liblist_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liblist',
            name='bookcheckoutstatus',
        ),
        migrations.AddField(
            model_name='liblist',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='liblist',
            name='book',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='liblists', to='libapp.Book'),
        ),
        migrations.AlterField(
            model_name='liblist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 21, 21, 44, 59, 18660)),
        ),
    ]
