# Generated by Django 2.0 on 2018-08-21 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0004_auto_20180821_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liblist',
            name='checked_out',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='liblist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 21, 22, 3, 44, 384179)),
        ),
    ]
